
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-rapnat}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Alissonkiss@12}
    ports:
      - "5432:5432"
    networks:
      - moverap-net
    restart: unless-stopped

  moverap:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:-rapnat}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-Alissonkiss@12}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - moverap-net

networks:
  moverap-net:
