
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rapnat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alissonkiss@12
    ports:
      - "5432:5432"
    networks:
      - moverap-net
    restart: unless-stopped

  moverap:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rapnat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Alissonkiss@12
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    networks:
      - moverap-net

networks:
  moverap-net:
