spring:

  application:
    name: rapnat
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/rapnat}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Alissonkiss@12}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
